-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


 

CREATE TABLE public.merchant
(
    "id " integer,
    name character(100) NOT NULL,
    id_merchant_category integer,
    PRIMARY KEY ("id ")
);

CREATE TABLE public.merchant_categories
(
    id integer,
    name character(100),
    PRIMARY KEY (id)
);

CREATE TABLE public.card_holder
(
    id integer,
    name text,
    PRIMARY KEY (id)
);

CREATE TABLE public.credit_card
(
    "card " character varying(100),
    id integer,
    PRIMARY KEY (id)
);

ALTER TABLE public.credit_card
    ADD FOREIGN KEY (id)
    REFERENCES public.card_holder (id)
    NOT VALID;


ALTER TABLE public.transactions
    ADD FOREIGN KEY (card)
    REFERENCES public.credit_card ("card ")
    NOT VALID;


ALTER TABLE public.merchant
    ADD FOREIGN KEY (id_merchant_category)
    REFERENCES public.merchant_categories (id)
    NOT VALID;


ALTER TABLE public.merchant
    ADD FOREIGN KEY ("id ")
    REFERENCES public.transactions (id_merchant)
    NOT VALID;

END;